import { link, imageWithAlt, seoMeta, portableText } from "./atoms";
import {
  ctaButton,
  navItem,
  faqItem,
  formField,
  testimonialCard,
  featureCardSmall,
  featureCardSideImage,
  featureCardToggle,
  serviceCardIcon,
  serviceCardSideImage,
} from "./molecules";
import { settings } from "./singletons";
import { nav, footer, form, person, blogPost, service, deliveryArea, page } from "./documents";
import {
  heroBgImage,
  heroSideImage,
  heroCentered,
  faqAccordions,
  faqCards,
  ctaBgImage,
  ctaCardCenter,
  ctaCardCenter2,
  ctaCards,
  featureCardsSmall,
  featureLightboxMarquee,
  featureGalleryMarquee,
  featureSideImage,
  featureToggleImage,
  servicesIcon,
  servicesSideImage,
  awardsSection,
  introSection,
  teamMemberCards,
  testimonialsColumns,
  testimonialsSwiper,
  contactSection,
  requestQuoteSection,
  becomePartnerSection,
  richText,
} from "./sections";

export const schemaTypes = [
  // Atoms
  link,
  imageWithAlt,
  seoMeta,
  portableText,
  // Molecules
  ctaButton,
  navItem,
  faqItem,
  formField,
  testimonialCard,
  featureCardSmall,
  featureCardSideImage,
  featureCardToggle,
  serviceCardIcon,
  serviceCardSideImage,
  // Singletons
  settings,
  // Documents
  nav,
  footer,
  form,
  person,
  blogPost,
  service,
  deliveryArea,
  page,
  // Sections (page block builder)
  heroBgImage,
  heroSideImage,
  heroCentered,
  faqAccordions,
  faqCards,
  ctaBgImage,
  ctaCardCenter,
  ctaCardCenter2,
  ctaCards,
  featureCardsSmall,
  featureLightboxMarquee,
  featureGalleryMarquee,
  featureSideImage,
  featureToggleImage,
  servicesIcon,
  servicesSideImage,
  awardsSection,
  introSection,
  teamMemberCards,
  testimonialsColumns,
  testimonialsSwiper,
  contactSection,
  requestQuoteSection,
  becomePartnerSection,
  richText,
];
