import { link, externalLink, internalLink, imageWithAlt, seoMeta, portableText } from "./atoms";
import {
  ctaButton,
  navItemDropdown,
  navObject,
  footerObject,
  faqItem,
  formField,
  testimonialCard,
  featureCardSmall,
  featureCardSideImage,
  featureCardToggle,
  serviceCardIcon,
  serviceCardSideImage,
} from "./molecules";
import { settings, robotsTxt } from "./singletons";
import { person, blogPost, page, category, deliveryArea, service } from "./documents";
import {
  heroBgImage,
  heroSideImage,
  heroCentered,
  faqAccordions,
  faqCards,
  ctaBgImage,
  ctaCardCenter,
  ctaCardCenter2,
  ctaCards,
  featureCardsSmall,
  featureLightboxMarquee,
  featureGalleryMarquee,
  featureSideImage,
  featureToggleImage,
  servicesIcon,
  servicesSideImage,
  awardsSection,
  introSection,
  teamMemberCards,
  testimonialsColumns,
  testimonialsSwiper,
  contactSection,
  richText,
  headingWithImage,
  featureVideo,
} from "./sections";

export const schemaTypes = [
  // Atoms
  link,
  externalLink,
  internalLink,
  imageWithAlt,
  seoMeta,
  portableText,
  // Molecules
  ctaButton,
  navItemDropdown,
  navObject,
  footerObject,
  faqItem,
  formField,
  testimonialCard,
  featureCardSmall,
  featureCardSideImage,
  featureCardToggle,
  serviceCardIcon,
  serviceCardSideImage,
  // Singletons
  settings,
  robotsTxt,
  // Documents
  person,
  blogPost,
  page,
  category,
  deliveryArea,
  service,
  // Sections (page block builder)
  heroBgImage,
  heroSideImage,
  heroCentered,
  faqAccordions,
  faqCards,
  ctaBgImage,
  ctaCardCenter,
  ctaCardCenter2,
  ctaCards,
  featureCardsSmall,
  featureLightboxMarquee,
  featureGalleryMarquee,
  featureSideImage,
  featureToggleImage,
  servicesIcon,
  servicesSideImage,
  awardsSection,
  introSection,
  teamMemberCards,
  testimonialsColumns,
  testimonialsSwiper,
  contactSection,
  richText,
  headingWithImage,
  featureVideo,
];
